export default {
	wix_navigation_menu: '.wixui-dropdown-menu',
	wix_navigation_menu_item: '.wixui-dropdown-menu__item',
	data_anchor_experience: '[data-anchor="dataItem-irm4m8o8"]',
	data_anchor_education: '[data-anchor="dataItem-irm4lazp"]',
	data_anchor_skills: '[data-anchor="dataItem-irm4ngvf"]',
	data_anchor_certifications: '[data-anchor="dataItem-lcnjrqyo"]',
	data_anchor_interests: '[data-anchor="dataItem-irm4nxd1"]',
	slide_show_gallery_items: '[data-testid="slide-show-gallery-items"]',
	slide_show_gallery: '[data-testid="slide-show-gallery"]',
	link_element: '[data-testid="linkElement"]',
	big_container: '[data-testid="container-bg"]',
	site_header: '#SITE_HEADER',
	contact_form: '.wixui-form',
	pro_gallery: '.pro-gallery-parent-container',
	pro_gallery: '.pro-gallery',
};
