name: Time of Day
on:
  push:
    branches: ['develop', 'main']
  pull_request:
    branches: ['develop', 'main']
  workflow_dispatch:

jobs:
  format-and-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Run Format
        run: npm run format-write
      - name: Install Dependencies
        run: npm ci
      - name: Install Frontend Dependencies
        run: cd frontend && pwd && ls && npm ci
  jest-run:
    runs-on: ubuntu-latest
    needs: [format-and-setup]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run jest tests
        run: npm run test
